SELECT *
FROM INFORMATION_SCHEMA.TABLES;

-- 1. 배치 마스터
CREATE TABLE BAT.BATCH_MASTER (
    BATCH_ID VARCHAR(50) PRIMARY KEY,
    BATCH_NM VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    USE_YN CHAR(1) DEFAULT 'Y',
    CRET_DT DATETIME2 DEFAULT SYSUTCDATETIME(),
    CHG_DT DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- 2. 배치 실행 이력
CREATE TABLE BAT.BATCH_RUN_HISTORY (
    RUN_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    BATCH_ID VARCHAR(50) NOT NULL,
    START_DT DATETIME2 NOT NULL,
    END_DT DATETIME2,
    STATUS VARCHAR(20) NOT NULL,
    RECORD_COUNT INT,
    ERROR_MESSAGE VARCHAR(2000),
    CRET_DT DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (BATCH_ID) REFERENCES BAT.BATCH_MASTER(BATCH_ID)
);

-- 3. 배치 파라미터
CREATE TABLE BAT.BATCH_PARAMETER (
    PARAM_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    BATCH_ID VARCHAR(50) NOT NULL,
    RUN_ID BIGINT NOT NULL,
    PARAM_NM VARCHAR(100) NOT NULL,
    PARAM_VAL VARCHAR(500),
    CRET_DT DATETIME2 DEFAULT SYSUTCDATETIME(),
    FOREIGN KEY (BATCH_ID) REFERENCES BAT.BATCH_MASTER(BATCH_ID),
    FOREIGN KEY (RUN_ID) REFERENCES dbo.BATCH_RUN_HISTORY(RUN_ID)
);


